/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'comisiones-crear': RouteRecordInfo<'comisiones-crear', '/comisiones-crear', Record<never, never>, Record<never, never>>,
    'comisiones-listado': RouteRecordInfo<'comisiones-listado', '/comisiones-listado', Record<never, never>, Record<never, never>>,
    'convocatorias-add': RouteRecordInfo<'convocatorias-add', '/convocatorias/add', Record<never, never>, Record<never, never>>,
    'convocatorias-detalles-id': RouteRecordInfo<'convocatorias-detalles-id', '/convocatorias/detalles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'convocatorias-edit-id': RouteRecordInfo<'convocatorias-edit-id', '/convocatorias/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'convocatorias-historialauditoria': RouteRecordInfo<'convocatorias-historialauditoria', '/convocatorias/historialauditoria', Record<never, never>, Record<never, never>>,
    'convocatorias-list': RouteRecordInfo<'convocatorias-list', '/convocatorias/list', Record<never, never>, Record<never, never>>,
    'convocatorias-vistapostul': RouteRecordInfo<'convocatorias-vistapostul', '/convocatorias/vistapostul', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'documentos-listado': RouteRecordInfo<'documentos-listado', '/documentos-listado', Record<never, never>, Record<never, never>>,
    'documentos-subir': RouteRecordInfo<'documentos-subir', '/documentos-subir', Record<never, never>, Record<never, never>>,
    'evaluaciones-id-infopostul': RouteRecordInfo<'evaluaciones-id-infopostul', '/evaluaciones/:id/infopostul', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'evaluaciones-list': RouteRecordInfo<'evaluaciones-list', '/evaluaciones/list', Record<never, never>, Record<never, never>>,
    'evaluaciones-revisardocumentos-id': RouteRecordInfo<'evaluaciones-revisardocumentos-id', '/evaluaciones/revisardocumentos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'evaluaciones-registrar': RouteRecordInfo<'evaluaciones-registrar', '/evaluaciones-registrar', Record<never, never>, Record<never, never>>,
    'formularios-add': RouteRecordInfo<'formularios-add', '/formularios/add', Record<never, never>, Record<never, never>>,
    'formularios-list': RouteRecordInfo<'formularios-list', '/formularios/list', Record<never, never>, Record<never, never>>,
    'instituciones-listado': RouteRecordInfo<'instituciones-listado', '/instituciones-listado', Record<never, never>, Record<never, never>>,
    'instituciones-registrar': RouteRecordInfo<'instituciones-registrar', '/instituciones-registrar', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'modulos-operaciones': RouteRecordInfo<'modulos-operaciones', '/modulos-operaciones', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'postulaciones-postulacion_id-documentos': RouteRecordInfo<'postulaciones-postulacion_id-documentos', '/postulaciones/:postulacion_id/documentos', { postulacion_id: ParamValue<true> }, { postulacion_id: ParamValue<false> }>,
    'postulaciones-estado-barra': RouteRecordInfo<'postulaciones-estado-barra', '/postulaciones/EstadoBarra', Record<never, never>, Record<never, never>>,
    'postulaciones-mispostul': RouteRecordInfo<'postulaciones-mispostul', '/postulaciones/mispostul', Record<never, never>, Record<never, never>>,
    'postulantes-add': RouteRecordInfo<'postulantes-add', '/postulantes/add', Record<never, never>, Record<never, never>>,
    'postulantes-list': RouteRecordInfo<'postulantes-list', '/postulantes/list', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'roles-permisos': RouteRecordInfo<'roles-permisos', '/roles-permisos', Record<never, never>, Record<never, never>>,
    'staffs': RouteRecordInfo<'staffs', '/staffs', Record<never, never>, Record<never, never>>,
    'tercera-page': RouteRecordInfo<'tercera-page', '/tercera-page', Record<never, never>, Record<never, never>>,
  }
}
